version: '3.8'

services:
  product-list-app:
    build:
      context: .
      dockerfile: Dockerfile


    restart: unless-stopped
    container_name: product-list-app

    ports:
      - 8080:8080
    stdin_open: true